dataset: ImageNet
subset: imagenette
res: 128
model: ConvNetD5
device: [0,1,2,3]

ipc: 10
syn_steps: 40
expert_epochs: 2
lr_img: 1000
lr_teacher: 0.01
buffer_path: ../buffer_storage/in1k
ema_decay: 0.9995
Iteration: 10000
batch_syn: 200

# 更新数据路径为绝对路径
data_path: /home/fangyuanchen/code/dataset/imagenet

# wandb
project: LRI-DD
name: imagenette_ipc10

num_eval: 1
eval_it: 500
skip_first_eva: False

lr_y: 2.0
Momentum_y: 0.9
threshold: 1.5
pix_init: samples_predicted_correctly
batch_train: 128

Sequential_Generation: True
min_start_epoch: 0
current_max_start_epoch: 10
max_start_epoch: 20
expansion_end_epoch: 1000

lr_lr: 0.00001

zca: False

interval: 100
loss_threshold: 0.25
model_name: ResNet18
target_layer_deep: 'layer4'
beta: 1.0